export const conditions = [
  { id: "anxiety", name: "Anxiety", icon: "brain", tone: "lavender" },
  { id: "depression", name: "Depression", icon: "sun", tone: "peach" },
  {
    id: "high-cholesterol",
    name: "High cholesterol",
    icon: "heart",
    tone: "rose",
  },
  {
    id: "high-blood-pressure",
    name: "High blood pressure",
    icon: "activity",
    tone: "mint",
  },
  {
    id: "type-2-diabetes",
    name: "Type 2 diabetes",
    icon: "activity",
    tone: "green",
  },
  {
    id: "seasonal-allergies",
    name: "Seasonal allergies",
    icon: "flower",
    tone: "yellow",
  },
  { id: "acne", name: "Acne", icon: "sun", tone: "pink" },
  { id: "asthma", name: "Asthma", icon: "wind", tone: "blue" },
] as const;
export type Medication = {
  id: string;
  name: string;
  brand: string;
  condition: string;
  terms: string;
  dose: string;
  quantity: string;
  price: number;
  color: string;
};
export const medications: Medication[] = [
  {
    id: "sertraline",
    name: "Sertraline",
    brand: "Generic Zoloft",
    condition: "anxiety",
    terms: "anxiety panic social anxiety",
    dose: "50 mg",
    quantity: "30 tablets",
    price: 9.6,
    color: "pink",
  },
  {
    id: "escitalopram",
    name: "Escitalopram",
    brand: "Generic Lexapro",
    condition: "anxiety",
    terms: "anxiety generalized anxiety",
    dose: "10 mg",
    quantity: "30 tablets",
    price: 8.2,
    color: "lavender",
  },
  {
    id: "buspirone",
    name: "Buspirone",
    brand: "Generic BuSpar",
    condition: "anxiety",
    terms: "anxiety generalized anxiety",
    dose: "10 mg",
    quantity: "60 tablets",
    price: 11.4,
    color: "mint",
  },
  {
    id: "fluoxetine",
    name: "Fluoxetine",
    brand: "Generic Prozac",
    condition: "depression",
    terms: "depression major depressive disorder",
    dose: "20 mg",
    quantity: "30 capsules",
    price: 7.8,
    color: "peach",
  },
  {
    id: "bupropion-xl",
    name: "Bupropion XL",
    brand: "Generic Wellbutrin XL",
    condition: "depression",
    terms: "depression major depressive disorder",
    dose: "150 mg",
    quantity: "30 tablets",
    price: 13.2,
    color: "pink",
  },
  {
    id: "duloxetine",
    name: "Duloxetine",
    brand: "Generic Cymbalta",
    condition: "depression",
    terms: "depression major depressive disorder",
    dose: "30 mg",
    quantity: "30 capsules",
    price: 12.1,
    color: "lavender",
  },
  {
    id: "atorvastatin",
    name: "Atorvastatin",
    brand: "Generic Lipitor",
    condition: "high-cholesterol",
    terms: "high cholesterol statin",
    dose: "20 mg",
    quantity: "30 tablets",
    price: 8.4,
    color: "lavender",
  },
  {
    id: "rosuvastatin",
    name: "Rosuvastatin",
    brand: "Generic Crestor",
    condition: "high-cholesterol",
    terms: "high cholesterol statin",
    dose: "10 mg",
    quantity: "30 tablets",
    price: 10.7,
    color: "pink",
  },
  {
    id: "simvastatin",
    name: "Simvastatin",
    brand: "Generic Zocor",
    condition: "high-cholesterol",
    terms: "high cholesterol statin",
    dose: "20 mg",
    quantity: "30 tablets",
    price: 6.9,
    color: "peach",
  },
  {
    id: "lisinopril",
    name: "Lisinopril",
    brand: "Generic Zestril",
    condition: "high-blood-pressure",
    terms: "high blood pressure hypertension",
    dose: "10 mg",
    quantity: "30 tablets",
    price: 5.2,
    color: "peach",
  },
  {
    id: "amlodipine",
    name: "Amlodipine",
    brand: "Generic Norvasc",
    condition: "high-blood-pressure",
    terms: "high blood pressure hypertension",
    dose: "5 mg",
    quantity: "30 tablets",
    price: 6.4,
    color: "mint",
  },
  {
    id: "losartan",
    name: "Losartan",
    brand: "Generic Cozaar",
    condition: "high-blood-pressure",
    terms: "high blood pressure hypertension",
    dose: "50 mg",
    quantity: "30 tablets",
    price: 7.1,
    color: "lavender",
  },
  {
    id: "metformin",
    name: "Metformin",
    brand: "Generic Glucophage",
    condition: "type-2-diabetes",
    terms: "type 2 diabetes blood sugar",
    dose: "500 mg",
    quantity: "60 tablets",
    price: 4.8,
    color: "mint",
  },
  {
    id: "glipizide",
    name: "Glipizide",
    brand: "Generic Glucotrol",
    condition: "type-2-diabetes",
    terms: "type 2 diabetes blood sugar",
    dose: "5 mg",
    quantity: "30 tablets",
    price: 7.3,
    color: "peach",
  },
  {
    id: "pioglitazone",
    name: "Pioglitazone",
    brand: "Generic Actos",
    condition: "type-2-diabetes",
    terms: "type 2 diabetes blood sugar",
    dose: "15 mg",
    quantity: "30 tablets",
    price: 9.1,
    color: "lavender",
  },
  {
    id: "cetirizine",
    name: "Cetirizine",
    brand: "Generic Zyrtec",
    condition: "seasonal-allergies",
    terms: "seasonal allergies allergy antihistamine",
    dose: "10 mg",
    quantity: "30 tablets",
    price: 6.5,
    color: "peach",
  },
  {
    id: "loratadine",
    name: "Loratadine",
    brand: "Generic Claritin",
    condition: "seasonal-allergies",
    terms: "seasonal allergies allergy antihistamine",
    dose: "10 mg",
    quantity: "30 tablets",
    price: 7.2,
    color: "mint",
  },
  {
    id: "fexofenadine",
    name: "Fexofenadine",
    brand: "Generic Allegra",
    condition: "seasonal-allergies",
    terms: "seasonal allergies allergy antihistamine",
    dose: "180 mg",
    quantity: "30 tablets",
    price: 10.3,
    color: "lavender",
  },
  {
    id: "tretinoin",
    name: "Tretinoin",
    brand: "Generic Retin-A",
    condition: "acne",
    terms: "acne topical retinoid cream",
    dose: "0.025% cream",
    quantity: "1 tube, 20 g",
    price: 24.2,
    color: "pink",
  },
  {
    id: "clindamycin-topical",
    name: "Clindamycin topical",
    brand: "Generic Cleocin T",
    condition: "acne",
    terms: "acne topical antibiotic gel",
    dose: "1% gel",
    quantity: "1 tube, 30 g",
    price: 18.6,
    color: "mint",
  },
  {
    id: "doxycycline",
    name: "Doxycycline",
    brand: "Generic Vibramycin",
    condition: "acne",
    terms: "acne oral antibiotic",
    dose: "100 mg",
    quantity: "30 capsules",
    price: 12.8,
    color: "peach",
  },
  {
    id: "albuterol",
    name: "Albuterol HFA",
    brand: "Generic Ventolin HFA",
    condition: "asthma",
    terms: "asthma breathing rescue inhaler",
    dose: "90 mcg",
    quantity: "1 inhaler, 18 g",
    price: 18.4,
    color: "lavender",
  },
  {
    id: "budesonide",
    name: "Budesonide",
    brand: "Pulmicort Flexhaler",
    condition: "asthma",
    terms: "asthma controller inhaler",
    dose: "90 mcg",
    quantity: "1 inhaler",
    price: 32.5,
    color: "mint",
  },
  {
    id: "montelukast",
    name: "Montelukast",
    brand: "Generic Singulair",
    condition: "asthma",
    terms: "asthma prevention controller",
    dose: "10 mg",
    quantity: "30 tablets",
    price: 11.9,
    color: "peach",
  },
];
export const pharmacies = [
  {
    id: "meadow",
    name: "Meadow Pharmacy",
    initials: "m",
    color: "mint",
    addition: 0,
  },
  {
    id: "juniper",
    name: "Juniper Drugstore",
    initials: "J",
    color: "lavender",
    addition: 3.75,
  },
  {
    id: "oak",
    name: "Oak & Hearth",
    initials: "o+h",
    color: "peach",
    addition: 7.4,
  },
];
export type Pharmacy = (typeof pharmacies)[number];
export const money = (amount: number) =>
  amount.toLocaleString("en-US", { style: "currency", currency: "USD" });
